install-*: various updates from dotfiles
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/scripts/install-pipsi b/scripts/install-pipsi
--- a/scripts/install-pipsi
+++ b/scripts/install-pipsi
@@ -1,14 +1,30 @@
 #!/bin/sh
 
-PATH=/usr/bin:/bin
+case $OSTYPE in
+    Darwin*)
+        PATH=/usr/bin:/bin
+        ;;
+esac
 
-pythonuserdir="$(python -c 'import site; print(site.getuserbase())')" || exit 1
-PATH="$pythonuserdir/bin:$PATH"
+if ! [ -e "$PIPSI_HOME/pipsi/bin/pipsi" ]; then
+    if which pyenv >/dev/null 2>&1; then
+        eval "$(pyenv init -)"
+    fi
+    pythonuserdir="$(python -c 'import site; print(site.getuserbase())')" || exit 1
+    PATH="$pythonuserdir/bin:$PATH"
 
-curl https://bootstrap.pypa.io/get-pip.py | python - --user
-if [ "$(which pip)" != "$pythonuserdir/bin/pip" ]; then
-    echo >&2 "Error in pip installation"
-    exit 1
+    if ! which pip >/dev/null 2>&1; then
+        curl https://bootstrap.pypa.io/get-pip.py | python - --user
+        if [ "$(which pip)" != "$pythonuserdir/bin/pip" ]; then
+            echo >&2 "Error in pip installation"
+            exit 1
+        fi
+    fi
+    if ! which virtualenv >/dev/null 2>&1; then
+        pip install --user --ignore-installed virtualenv
+    fi
+    curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python
+else
+    . "$PIPSI_HOME/pipsi/bin/activate"
+    pip install -U pipsi
 fi
-pip install --user --ignore-installed virtualenv
-curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python
